CREATE TABLE IF NOT EXISTS user(
    id INT NOT NULL UNIQUE AUTO_INCREMENT,
    username VARCHAR (127) NOT NULL UNIQUE,
    email VARCHAR (127) NOT NULL UNIQUE,
    password VARCHAR (127) NOT NULL,
    PRIMARY KEY (id)
)